---
# tasks file for ansible-role-doas

- include_vars: "{{ ansible_os_family }}.yml"

- name: Create doas.conf
  template:
    src: doas.conf.j2
    dest: "{{ doas_conf_file }}"
    mode: "{{ doas_conf_file_mode }}"
    validate: doas -C %s
