---
# tasks file for ansible-role-doas

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ doas_log_dir }}"
    mode: 0755
    owner: "{{ doas_user }}"
    group: "{{ doas_group }}"
    state: directory
  notify: Restart doas

- name: Create db directory
  file:
    path: "{{ doas_db_dir }}"
    mode: 0755
    owner: "{{ doas_user }}"
    group: "{{ doas_group }}"
    state: directory
  notify: Restart doas

- name: Create doas.conf
  template:
    src: doas.conf.j2
    dest: "{{ doas_conf_file }}"
    validate: echo %s
  notify: Restart doas

- name: Start doas
  service:
    name: "{{ doas_service }}"
    enabled: true
    state: started
